# Generated by Django 4.0.1 on 2022-03-18 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('tel_number', models.CharField(max_length=55, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=155, null=True)),
                ('last_name', models.CharField(blank=True, max_length=155, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiseasedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('telephone_number', models.CharField(max_length=55)),
                ('email_address', models.EmailField(max_length=254)),
                ('describe_your_condition', models.TextField(max_length=300, verbose_name='Brief information about your condition')),
                ('time_procedure', models.PositiveIntegerField(verbose_name='How many times treatments do you want?')),
                ('is_doctor_view', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Diseased User',
                'verbose_name_plural': 'Diseased Users',
            },
        ),
        migrations.CreateModel(
            name='SpecialDoctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('special_type', models.CharField(max_length=255)),
                ('procedure_cost', models.PositiveIntegerField(verbose_name='The cost of a one-time procedure')),
            ],
            options={
                'abstract': False,
            },
            bases=('diseased.user',),
        ),
        migrations.CreateModel(
            name='StatusDiseasedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accept', 'Accept'), ('Refuse', 'Refuse')], max_length=10)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('diseased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_diseased', to='diseased.diseaseduser')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_status_diseased', to='diseased.specialdoctor')),
            ],
        ),
        migrations.AddField(
            model_name='diseaseduser',
            name='type_of_doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diseased', to='diseased.specialdoctor'),
        ),
    ]
